spring:
  jpa:
    open-in-view: true
    generate-ddl: false
    hibernate:
      ddl-auto: none

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus, health, info

#management:
#  endpoints:
#    web:
#      exposure:
#        include: env, info, health

#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#    health:
#      show-details: 'always'